### ISSUE TITLE
Replace RFC 7807 with RFC 9457

### ISSUE THREAD

**Issue by codello** [Karaoke-Manager/karman#50]
[RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) obsoletes [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807). We should update this repo accordingly:

- [x] Check if we are compliant with [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457)
- [ ] Update API Spec #57
- [ ] Update documentation comments #57
- [ ] Update Code, if necessary #57

**Comment by codello** [comment]
In order to be compliant with RFC 9457 we should make the following changes:

- Update the 422 response to use [JSON Pointers](https://www.rfc-editor.org/rfc/rfc9457#RFC6901) instead of the dot-syntax. This is not required by RFC 9457 but seems to be a more standardized way of handling these kinds of errors. See [Section 3](https://www.rfc-editor.org/rfc/rfc9457#name-the-problem-details-json-ob) of RFC 9457.
- We should use the TAG scheme for error types to identify them as non-resolvable URIs (as long as we don't have dedicated documentation for error types). As long as we don't have a dedicated domain we could use the `tag:codello.dev,2020:karman/problems:<id>` namespace. I think the goal should be to provide this kind of documentation and thus use https URLs for problem types in the end.
